### ISSUE TITLE
Vertical align

### ISSUE THREAD

**Issue by lefoy** [jaebradley/atomify#14]
The marquee text was offset for me, I added this CSS to my stylesheet and it works great now.

```
.spotify-setting-details,
.spotify-music-details {
    vertical-align: middle;
}
``` 

Before: ![](https://i.gyazo.com/d25a862ffd18b0a17ae1159ad4d152f4.png)
After: ![](https://i.gyazo.com/857433b84754746b5fabd4fa02809fa2.png)

**Comment by jaebradley** [comment]
@lefoy great! much appreciated - let me see if I can work that into a PR. Feel free to PR too!

**Comment by lefoy** [comment]
I can't easily send a PR right now (at work atm) but I wanted to at least share my fix :)
