### ISSUE TITLE
Scrolling is really distracting - Option to make the text static with truncation?

### ISSUE THREAD

**Issue by ndbroadbent** [jaebradley/atomify#18]
I find it really distracting to have some text constantly moving at the bottom of the window.

Would it be possible to add an option to make the text static, and just truncate long titles? And if the bar was a little wider, I think most track titles would fit without any truncation. Maybe you show the full artist and title on hover.

How difficult would it be to add this?

**Comment by ndbroadbent** [comment]
Sorry! I found a different plugin that has static text, so this one works for me: https://atom.io/packages/atom-spotify2

**Comment by jaebradley** [comment]
![alt-text](https://media0.giphy.com/media/l0MYHMtWbY8ASVWoM/giphy.gif)

**Comment by jaebradley** [comment]
Yeah, that makes sense as a feature - the trickiness would be implementing the dual states because they would live in two different places; the static text would live above the status bar.
