### ISSUE TITLE
Suggestion: Clickable next button

### ISSUE THREAD

**Issue by ahinkle** [jaebradley/atomify#22]
I LOVE this Plugin. Probably my most favorite out there! 
My only issue is I wish there was an easy way to skip the song using the interface. 
Who actually uses the Shuffle, repeat buttons? (Ok maybe some do but there is room at that bottom bar) 

Thank you!

**Comment by jaebradley** [comment]
@ahinkle thanks for opening this issue!

Do you know about the keyboard shortcuts? 

#### Previous song
`alt` + `control` + `j`

#### Next song
`alt` + `control` + `l`

**Comment by jaebradley** [comment]
@ahinkle I'm closing this for now since I haven't heard back from you and since there are already keyboard shortcuts.
