### ISSUE TITLE
Previous track not working

### ISSUE THREAD

**Issue by tylerzika** [jaebradley/atomify#23]
Hitting `(Alt + Ctrl + J)` doesn't work for me in going to the previous. All other Keybindings appear to work fine.

**Comment by jaebradley** [comment]
@tylerzika thanks for bringing this up - this is probably due to a keybinding conflict with another Atom package.

**Comment by jaebradley** [comment]
@tylerzika is this is a keybinding conflict? If so, I'm not sure this is an issue with the Atomify package...
