### ISSUE TITLE
Any possibility of thumbs up/down?

### ISSUE THREAD

**Issue by spectralsun** [jaebradley/atomify#26]
Would be cool to be able to thumbs up/down songs that are play off of radio!

**Comment by jaebradley** [comment]
@spectralsun definitely a great idea! Unfortunately (as far as I can tell), [the Spotify Applescript API ](https://developer.spotify.com/applescript-api/) does not support that action and since this plugin sits on top of that API, it too cannot support that action. :-(

**Comment by Hum4n01d** [comment]
Dang :(

**Comment by jaebradley** [comment]
Closing this for now since the Spotify Applescript API does not support this action.
